/**
 * IN-CLASS ASSESSMENT: Movie API
 * Total: 10 marks
 * Time: 170 minutes
 *
 * INSTRUCTIONS:
 * Create a simple Movie API using Express, TypeScript, and MongoDB.
 * Complete all 10 tasks marked with TODO comments below.
 * Each task is worth 1 mark.
 *
 * SETUP & RUN:
 * 1. Install dependencies:
 *    npm install
 *
 * 2. Create a .env file (copy from .env.example):
 *    DB_CONN_STRING=mongodb+srv://username:password@cluster.mongodb.net/
 *    DB_NAME=movieDB
 *    COLLECTION_NAME=movies
 *
 * 3. Run the development server:
 *    npm run dev
 *    (Server will start at http://localhost:5000)
 *
 * 4. Test your endpoints using Postman, Thunder Client, or curl
 *
 * BEFORE YOU START:
 * - Read through ALL TODO tasks first
 * - Look at the MOVIE SCHEMA below
 * - Reference your previous sushi API code if needed
 *
 * MOVIE SCHEMA:
 * {
 *   _id: ObjectId (auto-generated by MongoDB)
 *   title: string (required)
 *   director: string (required)
 *   year: number (required, must be between 1900 and current year)
 *   rating: number (required, must be between 1 and 10)
 * }
 */
export {};
//# sourceMappingURL=in-class-assessment.d.ts.map